from app.services.auth_service import AuthService
from app.services.auditoria_service import AuditoriaService
from app.services.almacen_articulo_service import AlmacenArticuloService
from app.services.almacen_prestamo_service import AlmacenPrestamoService
from app.services.almacen_devolucion_service import AlmacenDevolucionService
from app.services.vehiculo_service import VehiculoService
from app.services.ruta_service import RutaService
from app.services.mantenimiento_service import MantenimientoService
